### ISSUE TITLE
Backport "AArch64: temporary fix for trig and log functions in jdk11u"

### ISSUE THREAD

**Issue by stooart-mon** [AdoptOpenJDK/openjdk-jdk11#2]
Some new intrinsics were found to be broken on Aarch64, and need to be disabled for correct operation on jdk11. Fixes to the algorithms will be included in jdk12, jdk11u 

The patches are:
  
https://src.fedoraproject.org/rpms/java-11-openjdk/blob/master/f/RHBZ-1628612-JDK-8210461-workaround-disable-aarch64-intrinsic.patch

https://src.fedoraproject.org/rpms/java-11-openjdk/blob/master/f/RHBZ-1630996-JDK-8210858-workaround-disable-aarch64-intrinsic-log.patch

From http://mail.openjdk.java.net/pipermail/jdk-updates-dev/2018-September/000155.html

The upstream bug is: https://bugs.openjdk.java.net/browse/JDK-8211105 which is marked as P1 for jdk11u.

**Comment by karianna** [comment]
I'll apply the patch to `dev` since its been accepted upstream.

**Comment by stooart-mon** [comment]
Let me know if you need any help testing.

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-jdk11/pull/3
