### ISSUE TITLE
why mmap use  physical memory but not cgroup memory

### ISSUE THREAD

**Issue by StephenLiuYa** [AdoptOpenJDK/openjdk-jdk11#5]

**Comment by karianna** [comment]
Hi @StephenLiuYa - Is this a problem specific to the AdoptOpenJDK build or a general comment about OpenJDK?

**Comment by StephenLiuYa** [comment]
@karianna 
adoptjdk-jdk11 can get cgroup memory limit，so I ask ‘why mmap use physical memory but not cgroup memory’
* for example，if I set the contianer memory limit to 1024m, but tomcat in the comtainer is also  running when set Xms bigger than 1024m

**Comment by karianna** [comment]
Hi @StephenLiuYa - So I think this is a question for the upstream OpenJDK project (I assume you're using our Hotspot build as opposed to OpenJ9).  You can sign up to the mailing lists here: https://mail.openjdk.java.net/mailman/listinfo - I'd recommend asking your question (with some extra detail) on the hotspot-dev mailing list to start with.
